/* 
 * Octopus Server API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.17.1+Branch.master.Sha.434caf20746e16780a8fab99f2fd4f4894a7283e
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

import (
	"time"
)

type Certificate struct {

	Id string `json:"Id,omitempty"`

	Notes string `json:"Notes,omitempty"`

	Name string `json:"Name,omitempty"`

	CertificateData string `json:"CertificateData,omitempty"`

	Password string `json:"Password,omitempty"`

	EnvironmentIds []string `json:"EnvironmentIds,omitempty"`

	TenantedDeploymentParticipation int32 `json:"TenantedDeploymentParticipation,omitempty"`

	TenantIds []string `json:"TenantIds,omitempty"`

	TenantTags []string `json:"TenantTags,omitempty"`

	Archived time.Time `json:"Archived,omitempty"`

	Created time.Time `json:"Created,omitempty"`

	ReplacedBy string `json:"ReplacedBy,omitempty"`
}
