/* 
 * Octopus Server API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.17.1+Branch.master.Sha.434caf20746e16780a8fab99f2fd4f4894a7283e
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

import (
	"time"
)

type EventNotificationSubscription struct {

	Filter EventNotificationSubscriptionFilter `json:"Filter,omitempty"`

	EmailTeams []string `json:"EmailTeams,omitempty"`

	EmailFrequencyPeriod string `json:"EmailFrequencyPeriod,omitempty"`

	EmailDigestLastProcessed time.Time `json:"EmailDigestLastProcessed,omitempty"`

	EmailDigestLastProcessedEventAutoId int64 `json:"EmailDigestLastProcessedEventAutoId,omitempty"`

	EmailShowDatesInTimeZoneId string `json:"EmailShowDatesInTimeZoneId,omitempty"`

	WebhookURI string `json:"WebhookURI,omitempty"`

	WebhookTeams []string `json:"WebhookTeams,omitempty"`

	WebhookLastProcessed time.Time `json:"WebhookLastProcessed,omitempty"`

	WebhookLastProcessedEventAutoId int64 `json:"WebhookLastProcessedEventAutoId,omitempty"`
}
