/* 
 * Octopus Server API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.17.1+Branch.master.Sha.434caf20746e16780a8fab99f2fd4f4894a7283e
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

import (
	"time"
)

type MachineResource struct {

	Id string `json:"Id,omitempty"`

	Name string `json:"Name,omitempty"`

	Thumbprint string `json:"Thumbprint,omitempty"`

	Uri string `json:"Uri,omitempty"`

	IsDisabled bool `json:"IsDisabled,omitempty"`

	EnvironmentIds []string `json:"EnvironmentIds,omitempty"`

	Roles []string `json:"Roles,omitempty"`

	MachinePolicyId string `json:"MachinePolicyId,omitempty"`

	TenantedDeploymentParticipation int32 `json:"TenantedDeploymentParticipation,omitempty"`

	TenantIds []string `json:"TenantIds,omitempty"`

	TenantTags []string `json:"TenantTags,omitempty"`

	Status int32 `json:"Status,omitempty"`

	HealthStatus int32 `json:"HealthStatus,omitempty"`

	HasLatestCalamari bool `json:"HasLatestCalamari,omitempty"`

	StatusSummary string `json:"StatusSummary,omitempty"`

	IsInProcess bool `json:"IsInProcess,omitempty"`

	Endpoint EndpointResource `json:"Endpoint,omitempty"`

	LastModifiedOn time.Time `json:"LastModifiedOn,omitempty"`

	LastModifiedBy string `json:"LastModifiedBy,omitempty"`

	Links map[string]string `json:"Links,omitempty"`
}
