/* 
 * Octopus Server API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.17.1+Branch.master.Sha.434caf20746e16780a8fab99f2fd4f4894a7283e
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type ActionTemplateSearchResource struct {

	Id string `json:"Id,omitempty"`

	Type_ string `json:"Type,omitempty"`

	Name string `json:"Name,omitempty"`

	Description string `json:"Description,omitempty"`

	Author string `json:"Author,omitempty"`

	Website string `json:"Website,omitempty"`

	IsInstalled bool `json:"IsInstalled,omitempty"`

	IsBuiltIn bool `json:"IsBuiltIn,omitempty"`

	Category string `json:"Category,omitempty"`

	CommunityActionTemplateId string `json:"CommunityActionTemplateId,omitempty"`

	HasUpdate bool `json:"HasUpdate,omitempty"`

	Links map[string]string `json:"Links,omitempty"`
}
