/* 
 * Octopus Server API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.17.1+Branch.master.Sha.434caf20746e16780a8fab99f2fd4f4894a7283e
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

import (
	"time"
)

type ActionTemplateUsageResource struct {

	Id string `json:"Id,omitempty"`

	ActionTemplateId string `json:"ActionTemplateId,omitempty"`

	DeploymentProcessId string `json:"DeploymentProcessId,omitempty"`

	ActionId string `json:"ActionId,omitempty"`

	ActionName string `json:"ActionName,omitempty"`

	StepId string `json:"StepId,omitempty"`

	StepName string `json:"StepName,omitempty"`

	ProjectId string `json:"ProjectId,omitempty"`

	ProjectName string `json:"ProjectName,omitempty"`

	ProjectSlug string `json:"ProjectSlug,omitempty"`

	Version string `json:"Version,omitempty"`

	LastModifiedOn time.Time `json:"LastModifiedOn,omitempty"`

	LastModifiedBy string `json:"LastModifiedBy,omitempty"`

	Links map[string]string `json:"Links,omitempty"`
}
