/* 
 * Octopus Server API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.17.1+Branch.master.Sha.434caf20746e16780a8fab99f2fd4f4894a7283e
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

import (
	"time"
)

type CertificateResource struct {

	Id string `json:"Id,omitempty"`

	Name string `json:"Name,omitempty"`

	Notes string `json:"Notes,omitempty"`

	CertificateData SensitiveValue `json:"CertificateData,omitempty"`

	Password SensitiveValue `json:"Password,omitempty"`

	EnvironmentIds []string `json:"EnvironmentIds,omitempty"`

	TenantedDeploymentParticipation int32 `json:"TenantedDeploymentParticipation,omitempty"`

	TenantIds []string `json:"TenantIds,omitempty"`

	TenantTags []string `json:"TenantTags,omitempty"`

	CertificateDataFormat int32 `json:"CertificateDataFormat,omitempty"`

	Archived time.Time `json:"Archived,omitempty"`

	ReplacedBy string `json:"ReplacedBy,omitempty"`

	SubjectDistinguishedName string `json:"SubjectDistinguishedName,omitempty"`

	SubjectCommonName string `json:"SubjectCommonName,omitempty"`

	SubjectOrganization string `json:"SubjectOrganization,omitempty"`

	IssuerDistinguishedName string `json:"IssuerDistinguishedName,omitempty"`

	IssuerCommonName string `json:"IssuerCommonName,omitempty"`

	IssuerOrganization string `json:"IssuerOrganization,omitempty"`

	SelfSigned bool `json:"SelfSigned,omitempty"`

	Thumbprint string `json:"Thumbprint,omitempty"`

	NotAfter time.Time `json:"NotAfter,omitempty"`

	NotBefore time.Time `json:"NotBefore,omitempty"`

	IsExpired bool `json:"IsExpired,omitempty"`

	HasPrivateKey bool `json:"HasPrivateKey,omitempty"`

	Version int32 `json:"Version,omitempty"`

	SerialNumber string `json:"SerialNumber,omitempty"`

	SignatureAlgorithmName string `json:"SignatureAlgorithmName,omitempty"`

	SubjectAlternativeNames []string `json:"SubjectAlternativeNames,omitempty"`

	CertificateChain []X509Certificate `json:"CertificateChain,omitempty"`

	LastModifiedOn time.Time `json:"LastModifiedOn,omitempty"`

	LastModifiedBy string `json:"LastModifiedBy,omitempty"`

	Links map[string]string `json:"Links,omitempty"`
}
