/* 
 * Octopus Server API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.17.1+Branch.master.Sha.434caf20746e16780a8fab99f2fd4f4894a7283e
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type PhaseProgressionResource struct {

	Id string `json:"Id,omitempty"`

	Name string `json:"Name,omitempty"`

	Blocked bool `json:"Blocked,omitempty"`

	Progress int32 `json:"Progress,omitempty"`

	Deployments []PhaseDeploymentResource `json:"Deployments,omitempty"`

	AutomaticDeploymentTargets []string `json:"AutomaticDeploymentTargets,omitempty"`

	OptionalDeploymentTargets []string `json:"OptionalDeploymentTargets,omitempty"`

	MinimumEnvironmentsBeforePromotion int32 `json:"MinimumEnvironmentsBeforePromotion,omitempty"`

	IsOptionalPhase bool `json:"IsOptionalPhase,omitempty"`
}
