/* 
 * Octopus Server API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.17.1+Branch.master.Sha.434caf20746e16780a8fab99f2fd4f4894a7283e
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

import (
	"time"
)

type RootResource struct {

	Id string `json:"Id,omitempty"`

	Application string `json:"Application,omitempty"`

	Version string `json:"Version,omitempty"`

	ApiVersion string `json:"ApiVersion,omitempty"`

	InstallationId string `json:"InstallationId,omitempty"`

	AuthenticationProviders []AuthenticationProviderElement `json:"AuthenticationProviders,omitempty"`

	AutoLoginEnabled bool `json:"AutoLoginEnabled,omitempty"`

	AnyAuthenticationProvidersSupportPasswordManagement bool `json:"AnyAuthenticationProvidersSupportPasswordManagement,omitempty"`

	ExtensionsCSS []string `json:"ExtensionsCSS,omitempty"`

	ExtensionsJavascript []string `json:"ExtensionsJavascript,omitempty"`

	ExtensionAngularModules []string `json:"ExtensionAngularModules,omitempty"`

	IsEarlyAccessProgram bool `json:"IsEarlyAccessProgram,omitempty"`

	LastModifiedOn time.Time `json:"LastModifiedOn,omitempty"`

	LastModifiedBy string `json:"LastModifiedBy,omitempty"`

	Links map[string]string `json:"Links,omitempty"`
}
