/* 
 * Octopus Server API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.17.1+Branch.master.Sha.434caf20746e16780a8fab99f2fd4f4894a7283e
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type UserPermissionSetResourcePermissions struct {

	None []UserPermissionRestriction `json:"None,omitempty"`

	AdministerSystem []UserPermissionRestriction `json:"AdministerSystem,omitempty"`

	ProjectEdit []UserPermissionRestriction `json:"ProjectEdit,omitempty"`

	ProjectView []UserPermissionRestriction `json:"ProjectView,omitempty"`

	ProjectCreate []UserPermissionRestriction `json:"ProjectCreate,omitempty"`

	ProjectDelete []UserPermissionRestriction `json:"ProjectDelete,omitempty"`

	ProcessView []UserPermissionRestriction `json:"ProcessView,omitempty"`

	ProcessEdit []UserPermissionRestriction `json:"ProcessEdit,omitempty"`

	VariableEdit []UserPermissionRestriction `json:"VariableEdit,omitempty"`

	VariableEditUnscoped []UserPermissionRestriction `json:"VariableEditUnscoped,omitempty"`

	VariableView []UserPermissionRestriction `json:"VariableView,omitempty"`

	VariableViewUnscoped []UserPermissionRestriction `json:"VariableViewUnscoped,omitempty"`

	ReleaseCreate []UserPermissionRestriction `json:"ReleaseCreate,omitempty"`

	ReleaseView []UserPermissionRestriction `json:"ReleaseView,omitempty"`

	ReleaseEdit []UserPermissionRestriction `json:"ReleaseEdit,omitempty"`

	ReleaseDelete []UserPermissionRestriction `json:"ReleaseDelete,omitempty"`

	DefectReport []UserPermissionRestriction `json:"DefectReport,omitempty"`

	DefectResolve []UserPermissionRestriction `json:"DefectResolve,omitempty"`

	DeploymentCreate []UserPermissionRestriction `json:"DeploymentCreate,omitempty"`

	DeploymentDelete []UserPermissionRestriction `json:"DeploymentDelete,omitempty"`

	DeploymentView []UserPermissionRestriction `json:"DeploymentView,omitempty"`

	EnvironmentView []UserPermissionRestriction `json:"EnvironmentView,omitempty"`

	EnvironmentCreate []UserPermissionRestriction `json:"EnvironmentCreate,omitempty"`

	EnvironmentEdit []UserPermissionRestriction `json:"EnvironmentEdit,omitempty"`

	EnvironmentDelete []UserPermissionRestriction `json:"EnvironmentDelete,omitempty"`

	MachineCreate []UserPermissionRestriction `json:"MachineCreate,omitempty"`

	MachineEdit []UserPermissionRestriction `json:"MachineEdit,omitempty"`

	MachineView []UserPermissionRestriction `json:"MachineView,omitempty"`

	MachineDelete []UserPermissionRestriction `json:"MachineDelete,omitempty"`

	ArtifactView []UserPermissionRestriction `json:"ArtifactView,omitempty"`

	ArtifactCreate []UserPermissionRestriction `json:"ArtifactCreate,omitempty"`

	ArtifactEdit []UserPermissionRestriction `json:"ArtifactEdit,omitempty"`

	ArtifactDelete []UserPermissionRestriction `json:"ArtifactDelete,omitempty"`

	FeedView []UserPermissionRestriction `json:"FeedView,omitempty"`

	EventView []UserPermissionRestriction `json:"EventView,omitempty"`

	LibraryVariableSetView []UserPermissionRestriction `json:"LibraryVariableSetView,omitempty"`

	LibraryVariableSetCreate []UserPermissionRestriction `json:"LibraryVariableSetCreate,omitempty"`

	LibraryVariableSetEdit []UserPermissionRestriction `json:"LibraryVariableSetEdit,omitempty"`

	LibraryVariableSetDelete []UserPermissionRestriction `json:"LibraryVariableSetDelete,omitempty"`

	ProjectGroupView []UserPermissionRestriction `json:"ProjectGroupView,omitempty"`

	ProjectGroupCreate []UserPermissionRestriction `json:"ProjectGroupCreate,omitempty"`

	ProjectGroupEdit []UserPermissionRestriction `json:"ProjectGroupEdit,omitempty"`

	ProjectGroupDelete []UserPermissionRestriction `json:"ProjectGroupDelete,omitempty"`

	TeamCreate []UserPermissionRestriction `json:"TeamCreate,omitempty"`

	TeamView []UserPermissionRestriction `json:"TeamView,omitempty"`

	TeamEdit []UserPermissionRestriction `json:"TeamEdit,omitempty"`

	TeamDelete []UserPermissionRestriction `json:"TeamDelete,omitempty"`

	UserView []UserPermissionRestriction `json:"UserView,omitempty"`

	UserInvite []UserPermissionRestriction `json:"UserInvite,omitempty"`

	UserRoleView []UserPermissionRestriction `json:"UserRoleView,omitempty"`

	UserRoleEdit []UserPermissionRestriction `json:"UserRoleEdit,omitempty"`

	TaskView []UserPermissionRestriction `json:"TaskView,omitempty"`

	TaskViewLog []UserPermissionRestriction `json:"TaskViewLog,omitempty"`

	TaskCreate []UserPermissionRestriction `json:"TaskCreate,omitempty"`

	TaskCancel []UserPermissionRestriction `json:"TaskCancel,omitempty"`

	TaskEdit []UserPermissionRestriction `json:"TaskEdit,omitempty"`

	InterruptionView []UserPermissionRestriction `json:"InterruptionView,omitempty"`

	InterruptionSubmit []UserPermissionRestriction `json:"InterruptionSubmit,omitempty"`

	InterruptionViewSubmitResponsible []UserPermissionRestriction `json:"InterruptionViewSubmitResponsible,omitempty"`

	BuiltInFeedPush []UserPermissionRestriction `json:"BuiltInFeedPush,omitempty"`

	BuiltInFeedAdminister []UserPermissionRestriction `json:"BuiltInFeedAdminister,omitempty"`

	BuiltInFeedDownload []UserPermissionRestriction `json:"BuiltInFeedDownload,omitempty"`

	ActionTemplateView []UserPermissionRestriction `json:"ActionTemplateView,omitempty"`

	ActionTemplateCreate []UserPermissionRestriction `json:"ActionTemplateCreate,omitempty"`

	ActionTemplateEdit []UserPermissionRestriction `json:"ActionTemplateEdit,omitempty"`

	ActionTemplateDelete []UserPermissionRestriction `json:"ActionTemplateDelete,omitempty"`

	LifecycleCreate []UserPermissionRestriction `json:"LifecycleCreate,omitempty"`

	LifecycleView []UserPermissionRestriction `json:"LifecycleView,omitempty"`

	LifecycleEdit []UserPermissionRestriction `json:"LifecycleEdit,omitempty"`

	LifecycleDelete []UserPermissionRestriction `json:"LifecycleDelete,omitempty"`

	AccountView []UserPermissionRestriction `json:"AccountView,omitempty"`

	AccountEdit []UserPermissionRestriction `json:"AccountEdit,omitempty"`

	AccountCreate []UserPermissionRestriction `json:"AccountCreate,omitempty"`

	AccountDelete []UserPermissionRestriction `json:"AccountDelete,omitempty"`

	AuditView []UserPermissionRestriction `json:"AuditView,omitempty"`

	TenantCreate []UserPermissionRestriction `json:"TenantCreate,omitempty"`

	TenantEdit []UserPermissionRestriction `json:"TenantEdit,omitempty"`

	TenantView []UserPermissionRestriction `json:"TenantView,omitempty"`

	TenantDelete []UserPermissionRestriction `json:"TenantDelete,omitempty"`

	TagSetCreate []UserPermissionRestriction `json:"TagSetCreate,omitempty"`

	TagSetEdit []UserPermissionRestriction `json:"TagSetEdit,omitempty"`

	TagSetDelete []UserPermissionRestriction `json:"TagSetDelete,omitempty"`

	MachinePolicyCreate []UserPermissionRestriction `json:"MachinePolicyCreate,omitempty"`

	MachinePolicyView []UserPermissionRestriction `json:"MachinePolicyView,omitempty"`

	MachinePolicyEdit []UserPermissionRestriction `json:"MachinePolicyEdit,omitempty"`

	MachinePolicyDelete []UserPermissionRestriction `json:"MachinePolicyDelete,omitempty"`

	ProxyCreate []UserPermissionRestriction `json:"ProxyCreate,omitempty"`

	ProxyView []UserPermissionRestriction `json:"ProxyView,omitempty"`

	ProxyEdit []UserPermissionRestriction `json:"ProxyEdit,omitempty"`

	ProxyDelete []UserPermissionRestriction `json:"ProxyDelete,omitempty"`

	SubscriptionCreate []UserPermissionRestriction `json:"SubscriptionCreate,omitempty"`

	SubscriptionView []UserPermissionRestriction `json:"SubscriptionView,omitempty"`

	SubscriptionEdit []UserPermissionRestriction `json:"SubscriptionEdit,omitempty"`

	SubscriptionDelete []UserPermissionRestriction `json:"SubscriptionDelete,omitempty"`

	TriggerCreate []UserPermissionRestriction `json:"TriggerCreate,omitempty"`

	TriggerView []UserPermissionRestriction `json:"TriggerView,omitempty"`

	TriggerEdit []UserPermissionRestriction `json:"TriggerEdit,omitempty"`

	TriggerDelete []UserPermissionRestriction `json:"TriggerDelete,omitempty"`

	CertificateView []UserPermissionRestriction `json:"CertificateView,omitempty"`

	CertificateCreate []UserPermissionRestriction `json:"CertificateCreate,omitempty"`

	CertificateEdit []UserPermissionRestriction `json:"CertificateEdit,omitempty"`

	CertificateDelete []UserPermissionRestriction `json:"CertificateDelete,omitempty"`

	CertificateExportPrivateKey []UserPermissionRestriction `json:"CertificateExportPrivateKey,omitempty"`
}
